url: https://phothinmg.github.io/
# site
title: Pho Thin
source: app
markdown: kramdown
kramdown:
  syntax_highlighter: none
sass:
  style: compressed
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-pagefind
  - jekyll-minify-js
exclude:
  - Makefile
collections:
  crafts:
    output: true
  blog:
    output: true
minify_js:
  enabled: true # disable to skip minification
  entry_dir: js
  output_dir: js # destination directory under site dest
  terser_opts:
    compress: true # enable compression
    mangle: true # enable name mangling
    source_map: true # produce .map files
jekyll_pagefind:
  quiet: true
nav_links:
  - text: Blog
    link: /blog
  - text: Projects
    link: "/#projects"
  - text: Contributions
    link: "/#contributions"
  - text: Crafts
    link: "/#crafts"
